stages:
- template: azure/stages.yml@templates
  parameters:
    minrust: false
- stage: coverage
  jobs:
  - job: grcov
    pool:
      vmImage: ubuntu-latest
    variables:
      cargo_incremental: 0
      rustflags: -Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads
    steps:
    - template: azure/install-rust.yml@templates
      parameters:
        rust: nightly
    - script: cargo build --verbose
      displayName: build
    - script: cargo test --verbose
      displayName: run tests
    - script: |
        curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
      displayName: install grcov
    - script: |
        zip -0 ccov.zip $(find . -name 'blacc*.gc*' -print)
        ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore-dir "/*" -o lcov.info
        bash <(curl -s https://codecov.io/bash) -f lcov.info
      displayName: collect coverage
      env:
        CODECOV_TOKEN: $(CODECOV_TOKEN)
- stage: pre_commit
  jobs:
  - job: pre_commit
    pool:
      vmImage: ubuntu-latest
    steps:
    - template: azure/install-rust.yml@templates
      parameters:
        rust: beta
        components:
        - rustfmt
        - clippy
    - task: UsePythonVersion@0
      inputs:
        versionSpec: 3.7
    - script: pip install pre-commit
      displayName: Install pre-commit
    - script: |
        if [ "$BUILD_REASON" = "pullrequest" ]; then
          TARGET=$(git merge-base "$SYSTEM_PULLREQUEST_SOURCEBRANCH" "origin/$SYSTEM_PULLREQUEST_TARGETBRANCH")
        else
          TARGET=$(git rev-parse "$BUILD_SOURCEVERSION"^)
        fi
        git diff-tree --no-commit-id --name-only -r "$TARGET" "$BUILD_SOURCEVERSION" | \
        xargs pre-commit run --verbose --files
      displayName: Run pre-commit hooks


resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: zsol
