stages:
- template: azure/stages.yml@templates
  parameters:
    minrust: false
- stage: pre-commit
  jobs:
  - job: pre-commit
    pool:
      vmImage: ubuntu-latest
    steps:
    - template: azure/install-rust.yml@templates
      parameters:
        rust: beta
        components:
        - rustfmt
        - clippy
    - task: UsePythonVersion@0
      inputs:
        versionSpec: 3.7
    - script: pip install pre-commit
      displayName: Install pre-commit
    - script: |
        if [ "$BUILD_REASON" = "pullrequest" ]; then
          TARGET=$(git merge-base "$SYSTEM_PULLREQUEST_SOURCEBRANCH" "origin/$SYSTEM_PULLREQUEST_TARGETBRANCH")
        else
          TARGET=$(git rev-parse "$BUILD_SOURCEVERSION"^)
        fi
        git diff-tree --no-commit-id --name-only -r "$TARGET" "$BUILD_SOURCEVERSION" | \
        xargs pre-commit run --verbose --files
      displayName: Run pre-commit hooks


resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: zsol
